apiVersion: v1
kind: Service
metadata:
  name: vite-react-service
spec:
  selector:
    app: vite-react-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007  # Optional: Minikube will auto-assign if omitted
